#!/usr/bin/env python
# coding: utf8
# Warning this file was originally generated by Create-BMOdescFile.py
# Nov 12 2025 changed FIX_Symbol on them all
# added field XferCategory to the desc table)
# ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,there are five possible splits on a transaction
# only XferSplit is covered by this table. It is only used by BAMN transactions currently
#             'XferSplit':'Tax:Income Tax', BANK             TxnUtil.setXfrPar
#             'FeeSplit' .. Buy,Sell,Cover,Short             TxnUtil.setCommissionPart
#             'SecSplit'  maybe FAKE used by all except BANK TxnUtil.setSecurityPart
#             'IncSplit'  Dividend,ROC,interest,DVF,MiscInc  TxnUtil.setIncomePart
#             'ExpSplit'  negative Div,MiscExp               TxnUtil.setExpensePart(expSplit)
# Desc44 .. not used
# FIXED_Symbol ,,, is always used
# FIXED_Activity .. . used if activity is missing and its ROC , checked if its BANK .. many Action remaps still done by BMO_Inx_new
# Symbol  .. not used yet .. could use to get the stock prices.
# Activity .. not used yet
# XferCategory .. used on BANK transactions

# This table is used by BMO_Inv_new.py

#global BMOdescTable

BMOdescTable = dict({
'ALARIS EQTY PARTNERS INC TR UN':
{'Desc44': 'ALARIS EQTY PARTNERS INC TR UN', 'FIXED_Symbol': 'AD-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'AD.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'ALLIED PROPERTIES REAL EST INV':
{'Desc44': 'ALLIED PROPERTIES REAL EST INV', 'FIXED_Symbol': 'AP-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'AP.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'ALGONQUIN POWER & UTILS':
{'Desc44': 'ALGONQUIN POWER & UTILS', 'FIXED_Symbol': 'AQN-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'AQN', 'Activity': 'Dividend','XferCategory': 'default'}
,

'ALTAGAS':
{'Desc44': 'ALTAGAS', 'FIXED_Symbol': 'ALA-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'ALA', 'Activity': 'Dividend','XferCategory': 'default'}
,
'ARC RESOURCES LTD':
{'Desc44': 'ARC RESOURCES LTD', 'FIXED_Symbol': 'ARX-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'ARX', 'Activity': 'Dividend','XferCategory': 'default'}
,
'ATRIUM MTG INVESTMENT CORP COM':
{'Desc44': 'ATRIUM MTG INVESTMENT CORP COM', 'FIXED_Symbol': 'AI-T', 'FIXED_Activity': 'Interest', 'Symbol': 'AI', 'Activity': 'Interest','XferCategory': 'default'}
,
'AUTOMOTIVE PPTYS REAL EST INVT':
{'Desc44': 'AUTOMOTIVE PPTYS REAL EST INVT', 'FIXED_Symbol': 'APR-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'APR.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'BMO COVERED CALL CDN BKS ETF S':
{'Desc44': 'BMO COVERED CALL CDN BKS ETF S', 'FIXED_Symbol': 'ZWB-T', 'FIXED_Activity': 'Interest', 'Symbol': 'ZWB', 'Activity': 'Interest','XferCategory': 'default'}
,
'BONTERRA ENERGY':
{'Desc44': 'BONTERRA ENERGY', 'FIXED_Symbol': 'BNE-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'BNE', 'Activity': 'Dividend','XferCategory': 'default'}
,
'BROMPTON SPLIT BANC CL-A SHS':
{'Desc44': 'BROMPTON SPLIT BANC CL-A SHS', 'FIXED_Symbol': 'SBC-T', 'FIXED_Activity': 'Interest', 'Symbol': 'SBC', 'Activity': 'Interest','XferCategory': 'default'}
,
'BROMPTON SPLIT BANC CORP CL-A SHS': # CIBC
{'Desc44': 'BROMPTON SPLIT BANC CORP CL-A SHS', 'FIXED_Symbol': 'SBC-T', 'FIXED_Activity': 'Interest', 'Symbol': 'SBC', 'Activity': 'Interest','XferCategory': 'default'}
,
'BROOKFIELD GLOBAL INFRASTRUCTU':
{'Desc44': 'BROOKFIELD GLOBAL INFRASTRUCTU', 'FIXED_Symbol': 'BGI-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'BGI.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'BROOKFIELD RENEWABLE CL A SUB':
{'Desc44': 'BROOKFIELD RENEWABLE CL A SUB', 'FIXED_Symbol': 'BEPC-T', 'FIXED_Activity': 'Interest', 'Symbol': ' ', 'Activity': 'Interest','XferCategory': 'default'}
,
'BROOKFIELD RENEWABLE NEW CL A':
{'Desc44': 'BROOKFIELD RENEWABLE NEW CL A', 'FIXED_Symbol': 'BEPC-T', 'FIXED_Activity': 'Short', 'Symbol': 'BEPC', 'Activity': 'Exchange','XferCategory': 'default'}
,
'BROOKFIELD RENEWABLE PARTNERS':
{'Desc44': 'BROOKFIELD RENEWABLE PARTNERS', 'FIXED_Symbol': 'BEP-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'BEP.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'BTB REAL EST INVT TR TR UNIT N':
{'Desc44': 'BTB REAL EST INVT TR TR UNIT N', 'FIXED_Symbol': 'BTB-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'BTB.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'CANOE EIT INC FD UNIT':
{'Desc44': 'CANOE EIT INC FD UNIT', 'FIXED_Symbol': 'EIT-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'EIT.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'CANSO CR  INC FD CL A UNIT':
{'Desc44': 'CANSO CR  INC FD CL A UNIT', 'FIXED_Symbol': 'PBY-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'PBY.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'CAPITAL POWER CORP':
{'Desc44': 'CAPITAL POWER CORP', 'FIXED_Symbol': 'CPX-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'CPX', 'Activity': 'Dividend','XferCategory': 'default'}
,
'CDN UTIL 4.5% CUM RDM SECND PR':
{'Desc44': 'CDN UTIL 4.5% CUM RDM SECND PR', 'FIXED_Symbol': 'CU-PR-F-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'CU.PR.F', 'Activity': 'Dividend','XferCategory': 'default'}
,
'CDN UTIL CL-A NON-VTG SHARES':
{'Desc44': 'CDN UTIL CL-A NON-VTG SHARES', 'FIXED_Symbol': 'CU-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'CU', 'Activity': 'Dividend','XferCategory': 'default'}
,
'CHARTWELL RETIREMENT RESIDENCE':
{'Desc44': 'CHARTWELL RETIREMENT RESIDENCE', 'FIXED_Symbol': 'CSH-UN-T', 'FIXED_Activity': 'ROC', 'Symbol': 'CSH.UN', 'Activity': ' ','XferCategory': 'default'}
,
'CHOICE PROPERTIES REAL EST INV':
{'Desc44': 'CHOICE PROPERTIES REAL EST INV', 'FIXED_Symbol': 'CHP-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'CHP.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'CHORUS AVIATION COM VTG & VAR':
{'Desc44': 'CHORUS AVIATION COM VTG & VAR', 'FIXED_Symbol': 'CHR-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'CHR', 'Activity': 'Cash in lieu','XferCategory': 'default'}
,
'CHORUS AVIATION VTG & VAR VTG':
{'Desc44': 'CHORUS AVIATION VTG & VAR VTG', 'FIXED_Symbol': 'CHR-T', 'FIXED_Activity': 'Short', 'Symbol': ' ', 'Activity': 'Exchange','XferCategory': 'default'}
,
'CI TECH GIANTS COVERED CALL ET':
{'Desc44': 'CI TECH GIANTS COVERED CALL ET', 'FIXED_Symbol': 'TXF-T', 'FIXED_Activity': 'Interest', 'Symbol': 'TXF', 'Activity': 'Interest','XferCategory': 'default'}
,
'CROMBIE REAL EST INVT TR UNITS':
{'Desc44': 'CROMBIE REAL EST INVT TR UNITS', 'FIXED_Symbol': 'CRR-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'CRR.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'CT REAL EST INVT TR UNIT':
{'Desc44': 'CT REAL EST INVT TR UNIT', 'FIXED_Symbol': 'CRT-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'CRT.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'DEREGISTRATION 210-90014-1-8':
{'Desc44': 'DEREGISTRATION 210-90014-1-8', 'FIXED_Symbol': 'FAKE-T', 'FIXED_Activity': 'BANK', 'Symbol': ' ', 'Activity': 'Withdrawal','XferCategory': 'M&B Pension'}
,
'E SPLIT CL A COM':
{'Desc44': 'E SPLIT CL A COM', 'FIXED_Symbol': 'ENS-T', 'FIXED_Activity': 'Interest', 'Symbol': 'ENS', 'Activity': 'Interest','XferCategory': 'default'}
,
'EMERA':
{'Desc44': 'EMERA', 'FIXED_Symbol': 'EMA-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'EMA', 'Activity': 'Dividend','XferCategory': 'default'}
,
'ENBRIDGE':
{'Desc44': 'ENBRIDGE', 'FIXED_Symbol': 'ENB-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'ENB', 'Activity': 'Dividend','XferCategory': 'default'}
,
'EXCHANGE INC CORP':
{'Desc44': 'EXCHANGE INC CORP', 'FIXED_Symbol': 'EIF-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'EIF', 'Activity': 'Dividend','XferCategory': 'default'}
,
'EXCO TECHNOLOGIES':
{'Desc44': 'EXCO TECHNOLOGIES', 'FIXED_Symbol': 'XTC-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'XTC', 'Activity': 'Dividend','XferCategory': 'default'}
,
'FAIRFAX FIN    4.25% 06DEC2027':
{'Desc44': 'FAIRFAX FIN    4.25% 06DEC2027', 'FIXED_Symbol': '303901AZ5-T', 'FIXED_Activity': 'Interest', 'Symbol': ' ', 'Activity': 'Interest','XferCategory': 'default'}
,
'FED TAX WITHHELD ON DEREG':
{'Desc44': 'FED TAX WITHHELD ON DEREG', 'FIXED_Symbol': 'FAKE-T', 'FIXED_Activity': 'BANK', 'Symbol': ' ', 'Activity': 'Federal tax','XferCategory': 'Tax:Income Tax'}
,
'FED TAX WITHHELD ON RIF PAY':
{'Desc44': 'FED TAX WITHHELD ON RIF PAY', 'FIXED_Symbol': 'FAKE-T', 'FIXED_Activity': 'BANK', 'Symbol': ' ', 'Activity': 'Federal tax','XferCategory': 'Tax:Income Tax'}
,
'FIRM CAP MTG INVESTMENT CORP':
{'Desc44': 'FIRM CAP MTG INVESTMENT CORP', 'FIXED_Symbol': 'FC-T', 'FIXED_Activity': 'DVF', 'Symbol': 'FC', 'Activity': 'Reinvestment','XferCategory': 'default'}
,
'FIRM CAP PROPERTY TR UNIT':
{'Desc44': 'FIRM CAP PROPERTY TR UNIT', 'FIXED_Symbol': 'FCD-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'FCD.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'FIRST NTL FINANCIAL CORP':
{'Desc44': 'FIRST NTL FINANCIAL CORP', 'FIXED_Symbol': 'FN-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'FN', 'Activity': 'Dividend','XferCategory': 'default'}
,
'FORTIS':
{'Desc44': 'FORTIS', 'FIXED_Symbol': 'FTS-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'FTS', 'Activity': 'Dividend','XferCategory': 'default'}
,
'GIBSON ENERGY COM':
{'Desc44': 'GIBSON ENERGY COM', 'FIXED_Symbol': 'GEI-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'GEI', 'Activity': 'Dividend','XferCategory': 'default'}
,
'GRANITE REAL EST INVT TR TR UN':
{'Desc44': 'GRANITE REAL EST INVT TR TR UN', 'FIXED_Symbol': 'GRT-UN-T', 'FIXED_Activity': 'ROC', 'Symbol': 'GRT.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'GREAT WEST LIFE PREF 5.25%':
{'Desc44': 'GREAT WEST LIFE PREF 5.25%', 'FIXED_Symbol': 'GWO-PR-S-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'GWO.PR.S', 'Activity': 'Dividend','XferCategory': 'default'}
,
'GST# R103854261':
{'Desc44': 'GST# R103854261', 'FIXED_Symbol': 'FAKE-T', 'FIXED_Activity': 'BANK', 'Symbol': ' ', 'Activity': 'Goods & Services Tax','XferCategory': 'Tax:GST'}
,
'H&R REAL EST INVT TR UNIT NEW':
{'Desc44': 'H&R REAL EST INVT TR UNIT NEW', 'FIXED_Symbol': 'HR-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'HR.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'HARVEST HEALTHCARE LEADERS INC':
{'Desc44': 'HARVEST HEALTHCARE LEADERS INC', 'FIXED_Symbol': 'HHL-T', 'FIXED_Activity': 'Interest', 'Symbol': 'HHL', 'Activity': 'Interest','XferCategory': 'default'}
,
'INNERGEX RENEWABLE ENERGY':
{'Desc44': 'INNERGEX RENEWABLE ENERGY', 'FIXED_Symbol': 'INE-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'INE', 'Activity': 'Dividend','XferCategory': 'default'}
,
'KEYERA':
{'Desc44': 'KEYERA', 'FIXED_Symbol': 'KEY-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'KEY', 'Activity': 'Dividend','XferCategory': 'default'}
,
'MACKENZIE GLBL HIGH YLD ETF UN':
{'Desc44': 'MACKENZIE GLBL HIGH YLD ETF UN', 'FIXED_Symbol': 'MHYB-NEO', 'FIXED_Activity': 'Interest', 'Symbol': 'MHYB', 'Activity': 'Interest','XferCategory': 'default'}
,
'MELCOR REAL EST INVT TR UNIT':
{'Desc44': 'MELCOR REAL EST INVT TR UNIT', 'FIXED_Symbol': 'MR-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'MR.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'MIDDLEFIELD REAL EST DIVID ETF':
{'Desc44': 'MIDDLEFIELD REAL EST DIVID ETF', 'FIXED_Symbol': 'MREL-T', 'FIXED_Activity': 'Interest', 'Symbol': 'MREL', 'Activity': 'Interest','XferCategory': 'default'}
,
'MULLEN GROUP':
{'Desc44': 'MULLEN GROUP', 'FIXED_Symbol': 'MTL-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'MTL', 'Activity': 'Dividend','XferCategory': 'default'}
,
'NORTHLAND POWER':
{'Desc44': 'NORTHLAND POWER', 'FIXED_Symbol': 'NPI-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'NPI', 'Activity': 'Dividend','XferCategory': 'default'}
,
'PARKLAND CORP COM':
{'Desc44': 'PARKLAND CORP COM', 'FIXED_Symbol': 'PKI-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'PKI', 'Activity': 'Dividend','XferCategory': 'default'}
,
'PEMBINA PIPELINE':
{'Desc44': 'PEMBINA PIPELINE', 'FIXED_Symbol': 'PPL-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'PPL', 'Activity': 'Dividend','XferCategory': 'default'}
,
'PEYTO EXPLORATION AND DEV':
{'Desc44': 'PEYTO EXPLORATION AND DEV', 'FIXED_Symbol': 'PEY-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'PEY', 'Activity': 'Dividend','XferCategory': 'default'}
,
'PREMIUM INC CL A NO PAR':
{'Desc44': 'PREMIUM INC CL A NO PAR', 'FIXED_Symbol': 'PIC-A-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'PIC.A', 'Activity': 'Dividend','XferCategory': 'default'}
,
'PRIMARIS REAL EST INVT TR UNIT':
{'Desc44': 'PRIMARIS REAL EST INVT TR UNIT', 'FIXED_Symbol': 'PMZ-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'PMZ.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'ROGERS SUGAR':
{'Desc44': 'ROGERS SUGAR', 'FIXED_Symbol': 'RSI-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'RSI', 'Activity': 'Dividend','XferCategory': 'default'}
,
'REAL EST SPLIT CL A SHARES':
{'Desc44': 'REAL EST SPLIT CL A SHARES', 'FIXED_Symbol': 'RS-T', 'FIXED_Activity': 'Interest', 'Symbol': 'RS', 'Activity': 'Interest','XferCategory': 'default'}
,
'RRIF PAYMENT':
{'Desc44': 'RRIF PAYMENT', 'FIXED_Symbol': 'FAKE-T', 'FIXED_Activity': 'BANK', 'Symbol': ' ', 'Activity': 'Payment','XferCategory': 'LIF Pension'}
,
'SAVARIA CORP':
{'Desc44': 'SAVARIA CORP', 'FIXED_Symbol': 'SIS-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'SIS', 'Activity': 'Dividend','XferCategory': 'default'}
,
'SLATE GROCERY REIT CL U UNITS':
{'Desc44': 'SLATE GROCERY REIT CL U UNITS', 'FIXED_Symbol': 'SGR-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'SGR.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'SMARTCENTRES REAL EST INVESTME':
{'Desc44': 'SMARTCENTRES REAL EST INVESTME', 'FIXED_Symbol': 'SRU-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'SRU.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'SOUTH BOW COM':
{'Desc44': 'SOUTH BOW COM', 'FIXED_Symbol': 'SOBO-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'SOBO', 'Activity': 'Dividend','XferCategory': 'default'}
,
'SUPERIOR PLUS':
{'Desc44': 'SUPERIOR PLUS', 'FIXED_Symbol': 'SPB-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'SPB', 'Activity': 'Dividend','XferCategory': 'default'}
,
'SURGE ENERGY COM NEW':
{'Desc44': 'SURGE ENERGY COM NEW', 'FIXED_Symbol': 'SGY-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'SGY', 'Activity': 'Dividend','XferCategory': 'default'}
,
'TFSA WITHDRAWAL 210-90026-1-4':
{'Desc44': 'TFSA WITHDRAWAL 210-90026-1-4', 'FIXED_Symbol': 'FAKE-T', 'FIXED_Activity': 'BANK', 'Symbol': 'TRP', 'Activity': 'Withdrawal','XferCategory': 'Unknown'}
,
'TC ENERGY COM':
{'Desc44': 'TC ENERGY COM', 'FIXED_Symbol': 'TRP-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'TRP', 'Activity': 'Dividend','XferCategory': 'default'}
,
'TC ENERGY CORP': # Scotia
{'Desc44': 'TC ENERGY CORP', 'FIXED_Symbol': 'TRP-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'TRP', 'Activity': 'Dividend','XferCategory': 'default'}
,
'TELUS':
{'Desc44': 'TELUS', 'FIXED_Symbol': 'T-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'T', 'Activity': 'Dividend','XferCategory': 'default'}
,
'TIMBERCREEK FINL COM':
{'Desc44': 'TIMBERCREEK FINL COM', 'FIXED_Symbol': 'TF-T', 'FIXED_Activity': 'Interest', 'Symbol': 'TF', 'Activity': 'Interest','XferCategory': 'default'}
,
'TRUE NORTH COML REAL EST INVT':
{'Desc44': 'TRUE NORTH COML REAL EST INVT', 'FIXED_Symbol': 'TNT-UN-T', 'FIXED_Activity': 'Interest', 'Symbol': 'TNT.UN', 'Activity': 'Interest','XferCategory': 'default'}
,
'VANGUARD FTSE CDN HIGH DIVID Y':
{'Desc44': 'VANGUARD FTSE CDN HIGH DIVID Y', 'FIXED_Symbol': 'VDY-T', 'FIXED_Activity': 'Interest', 'Symbol': 'VDY', 'Activity': 'Interest','XferCategory': 'default'}
,
'VERMILION ENERGY':
{'Desc44': 'VERMILION ENERGY', 'FIXED_Symbol': 'VET-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'VET', 'Activity': 'Dividend','XferCategory': 'default'}
,
'WAJAX CORP':
{'Desc44': 'WAJAX CORP', 'FIXED_Symbol': 'WJX-T', 'FIXED_Activity': 'Dividend', 'Symbol': 'WJX', 'Activity': 'Dividend','XferCategory': 'default'}
,
'WITHDRAWAL FEE':
{'Desc44': 'WITHDRAWAL FEE', 'FIXED_Symbol': 'FAKE-T', 'FIXED_Activity': 'BANK', 'Symbol': ' ', 'Activity': 'De-registration fee','XferCategory': 'Bank Fees'}
})
